_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 1 #

#min_epochs: 1
# max_epochs: 10
#max_steps: 200000
# max_steps: 50000
# val_check_interval: 20 # 1000

weights_summary: null
progress_bar_refresh_rate: 5
resume_from_checkpoint: null

gradient_clip_val: 1 # 0.1
gradient_clip_algorithm: "norm"
