# @package _global_

# specify here default training configuration
defaults:
  - trainer: default.yaml
  - model: seq2seq.yaml
  - datamodule: grid.yaml
  - callbacks: default.yaml # set this to null if you don't want to use callbacks
  - logger: wandb #null # set logger here or use command line (e.g. `python run.py logger=wandb`)

  - experiment: null
  - hparams_search: null

  - hydra: default.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog
  - _self_

mode: train # ??? # train, evaluation, evaluation_from_file

# path to original working directory
work_dir: ${hydra:runtime.cwd}
# Verbose explanation: hydra hijacks the working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory

# path to folder with data
data_dir: ${work_dir}/data/

run_name: ${model.nn_params.name} # ??? # Will be used for logging

# use `python run.py debug=true` for easy debugging!
# this will run 1 train, val and test loop with only 1 batch
# equivalent to running `python run.py trainer.fast_dev_run=true`
# (this is placed here just for easier access from command line)
debug: False
debug_ckpt_path: "/home/martin_vm/GENIE/logs/runs/2021-10-03-23-45-51---real__100/checkpoints/model-98220-0.0000.ckpt"

# pretty print config at the start of the run using Rich library
print_config: False

# disable python warnings if they annoy you
ignore_warnings: True

# check performance on test set, using the best model achieved during training
# lightning chooses best model based on metric specified in checkpoint callback
test_after_training: True

seed: 123
